In [9]:
#Numpy Tutorial

In [15]:
#How to import numpy
import numpy as np

In [19]:
#zeros function -> creates array with 0s
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
#creating 2D array -> use tuple
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (e.g. 3*4=12)


In [33]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
a.shape

(4, 4)

In [43]:
#ndim -> len(a.shape)
a.ndim

2

In [49]:
#to find the total elements
a.size

16

## N-dimensional arrays
You can also create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape `(2,3,4)`:

In [61]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [65]:
#np array's type is ndarray
type(np.zeros(1))

numpy.ndarray

In [69]:
#ones fucntion create array with 1's
np.ones(3)

array([1., 1., 1.])

In [77]:
#np.full function fills the array with the given value.
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [83]:
#np.empty -> An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):
np.empty(2)

array([0., 0.])

In [89]:
#np.array -> to create array of ndarray type
np.array([1,2,3])

array([1, 2, 3])

In [93]:
#np.arange -> create array with range
np.arange(1, 5)

array([1, 2, 3, 4])

In [103]:
#also we can provide a step parameter
np.arange(1,6,0.3)

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8])

In [107]:
print(np.arange(0, 5/3, 1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333334]


np.random module has tons of functions in it.

In [113]:
np.random.rand(5)

array([0.00199887, 0.46373047, 0.81591702, 0.71080955, 0.18931921])

In [117]:
np.random.randn(6)  #includes negative values

array([ 1.27755137, -0.7536977 , -1.29272132, -0.05391702,  0.58347225,
       -1.35734822])

In [119]:
# np.fromfunction -> You can also initialize an `ndarray` using a function:

In [121]:
def my_function(z, y, x):
    return x + 10 * y + 100 * z

np.fromfunction(my_function, (3, 2, 10))

array([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]],

       [[100., 101., 102., 103., 104., 105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114., 115., 116., 117., 118., 119.]],

       [[200., 201., 202., 203., 204., 205., 206., 207., 208., 209.],
        [210., 211., 212., 213., 214., 215., 216., 217., 218., 219.]]])